name: 'home_maintenance'
description: 'Create Issues for various seasonal home maintenance tasks'
inputs:
  repo-nwo:
    description: 'the owner and name of the repo where issues will be created, e.g. maxbeizer/home_maintenance'
    required: true
  github-token:
    description: 'the github_token from the action'
    required: true
  path-to-data:
    description: 'the path to a csv of tasks'
    required: false
  time-frame:
    description: 'seasonal or all tasks should be converted to issues'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.repo-nwo }}
    - ${{ inputs.path-to-data }}
    - ${{ inputs.time-frame }}
